### ISSUE TITLE
Bot will not respond when choosing between nonitems

### ISSUE THREAD

**Issue by MatthewCech** [AlexStewartCode/KittyBot#4]
**Expected**
Using a series of commas should return an error from the bot

**Actual**
This breaks the bot, and there is no response.

**Repro**
- Start the bot
- Run command `!choose ,,,,,,,,,,,` (or with any number of multiple commas)
- Observe lack of response

**Comment by AlexStewartCode** [comment]
Fixed

Edited in cheeky response when finding an empty string
