### ISSUE TITLE
Roll improperly formats when providing a single number

### ISSUE THREAD

**Issue by MatthewCech** [AlexStewartCode/KittyBot#6]
**Expected**
Proving a value to roll that's a single value with no modifiers should just be the value.

**Actual**
This breaks the bot, and some placeholder values appear to be returned. `!roll 1` returns the following:
```
Roll
1
Steps
```Final value 
1```
```

**Repro**
- Start the bot
- Run the command `!roll X` with any single value (`!roll 1` for example) 
- Observe the result

**Comment by AlexStewartCode** [comment]
Edited roll function, had incorrect index array set.
