### ISSUE TITLE
Tagging multiple people using !trade results in the wrong error

### ISSUE THREAD

**Issue by MatthewCech** [AlexStewartCode/KittyBot#7]
**Expected**
Using the command `!trade @User @User 10` results in a unique error about multiple mentions or similar

**Actual**
Using the command `!trade @User @User` results in an error about 'not a number' instead of an error clarifying that you can't tag multiple users

**Repro**
- Start the bot
- Use the trade command with two existing users
- Observe resulting error message

**Comment by AlexStewartCode** [comment]
Fixed, added check for multiple users being tagged.
